name: csbm
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pyside6=6.8.0.2
  - gmpy2=2.1.5
  - pip:
    - accelerate==1.2.0
    - backports.tarfile==1.2.0
    - brotli==1.1.0
    - colorama==0.4.6
    - dall-e==0.1
    - einops==0.8.0
    - flash-attn==2.7.3
    - fqdn==1.5.1
    - h2==4.1.0
    - importlib-metadata==8.0.0
    - isoduration==20.11.0
    - jaraco.collections==5.1.0
    - jsonpointer==3.0.0
    - jupyter==1.1.1
    - lor-deckcodes==5.0.0
    - munkres==1.1.4
    - omegaconf==2.3.0
    - pip-chill==1.0.3
    - pot==0.9.5
    - pysocks==1.7.1
    - pytorch-fid==0.3.0
    - pytorch-lightning==2.4.0
    - reportlab==4.2.5
    - rlpycairo==0.2.0
    - scikit-learn==1.6.0
    - seaborn==0.13.2
    - shiboken6==6.8.0.2
    - sqlalchemy==2.0.36
    - torch-ema==0.3
    - torch-fidelity==0.3.0
    - torchaudio==2.4.1
    - transformers==4.48.0
    - unicodedata2==15.1.0
    - uri-template==1.3.0
    - wandb==0.19.0
    - webcolors==24.11.1
    - zstandard==0.23.0