model:
  base_learning_rate: 4.5e-06
  target: ldm.models.autoencoder.AutoencoderKL
  params:
    monitor: val/rec_loss
    embed_dim: 4
    ddconfig:
      double_z: true
      z_channels: 4
      resolution: 128
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminator
      params:
        disc_start: 30001
        kl_weight: 1.0e-06
        disc_weight: 0.5
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 16
    num_workers: 8
    train:
      target: ldm.data.custom.CustomTrain
      params:
        training_images_list_file: /trinity/home/g.ksenofontov/Projects/taming-transformers/data/celeba/celeba_train.txt
        size: 128
    validation:
      target: ldm.data.custom.CustomTest
      params:
        test_images_list_file: /trinity/home/g.ksenofontov/Projects/taming-transformers/data/celeba/celeba_test.txt
        size: 128
