data:
  type: images # choices: "toy", "images", "quantized_images", "texts"
  dataset: cmnist
  dim: 32
  num_categories: 256
  num_timesteps: 25
  num_skip_steps: 4
  coupling_type: independent # choices: "independent", "prior"
model:
  in_channels: 3
  num_channels: 64
  num_layers: 2
  ch_mults:
    - 1
    - 2
    - 2
    - 2
  attention_resolution: 16
  num_groups: 32
  num_att_heads: 4
  dropout: 0.1
prior:
  alpha: 0.01
  type: uniform # choices: "uniform", "gaussian", "von_mises"
train:
  batch_size: 128
  gradient_accumulation_steps: 1
  iterations: 20
  prior_iterations: 5
  inner_iterations: 20000
  use_mini_batch: false
  ce_loss_coeff: 0.001
  kl_loss_coeff: 1
  ema_decay: 0.9999
  optimizer:
    lr: 0.0002
    betas: [0.95, 0.99]
eval:
  freq: 1000
  num_samples: 25
  num_trajectories: 4 # How many trajecotries
  num_translations: 2 # How many times sample trajecotry from single point
