[data]
type = "quantized_images" # choices: "toy", "images", "quantized_images"
dim = 128
latent_dim = 32
num_categories = 256
num_timesteps = 100
num_skip_steps = 1
coupling_type = "independent" # choices: "independent", "prior", "mini_batch"

[model]
in_channels = 1
num_channels = 64
num_layers = 2
ch_mults = [1, 2, 4]
attention_resolution = 16
num_groups = 32
num_att_heads = 4
dropout = 0.1

[vq]
checkpoint = 'checkpoints/last.ckpt'
embed_dim = 4
n_embed = 256

[vq.ddconfig]
double_z = false
z_channels = 4
resolution = 128
in_channels = 3
out_ch = 3
ch = 128
ch_mult = [1, 2, 4]
num_res_blocks = 2
attn_resolutions = [32]
dropout = 0

[prior]
alpha = 0.05
type = "gaussian" # choices: "uniform", "gaussian", "random_neighbour", "von_mises"

[train]
batch_size = 128
iterations = 20
prior_iterations = 5
inner_iterations = 20000
lr = 0.0004
ce_loss_coeff = 0.001
kl_loss_coeff = 1.0
ema_decay = 0.999

[eval]
freq = 1000
num_samples = 25
num_trajectories = 4 # How many trajecotries
num_translations = 2 # How many times sample trajecotry from single point
