data:
  type: toy # choices: "toy", "images", "quantized_images"
  dim: 2
  num_categories: 50
  num_timesteps: 100
  num_skip_steps: 1
  coupling_type: independent # choices: "independent", "prior"
model:
  timestep_dim: 2
  layers: [128, 128, 128]
prior:
  alpha: 0.01
  type: gaussian # choices: "uniform", "gaussian", "von_mises"
train:
  batch_size: 512
  gradient_accumulation_steps: 1
  iterations: 10
  prior_iterations: 10
  inner_iterations: 20000
  use_mini_batch: false
  ce_loss_coeff: 0.001
  kl_loss_coeff: 1
  ema_decay: 0.999
  optimizer:
    lr: 0.0004
    betas: [0.95, 0.99]
    # weight_decay: 4.5e-2
eval:
  freq: 1000
  num_samples: 1024
  num_trajectories: 2 # How many trajecotries
  num_translations: 3 # How many times sample trajecotry from single point
